const mysteryHome = {
  countdownTarget: "2026-08-01T17:30:00",
};

const mysterySteps = [
  {
    id: "uppdrag-1",
    page: "uppdrag-1.html",
    title: "Ordlåset",
    unlockAt: null,
    hintUnlockAt: "2026-08-01T17:30:00",
    hintText: "Brudens smeknamn",
    requires: null,
    clue: "Lös det fem bokstäver långa ordet för att komma vidare.",
    answer: "SARRI",
    puzzle: {
      type: "wordle",
      answer: "SARRI",
      maxAttempts: null,
      visibleRows: 6,
    },
  },
  {
    id: "uppdrag-2",
    page: "uppdrag-2.html",
    title: "Trådarna mellan oss",
    unlockAt: null,
    hintUnlockAt: "2026-08-01T18:00:00",
    hintText: "Placeholder-ledtråd för uppdrag 2.",
    requires: "uppdrag-1",
    clue: "Hitta fyra dolda samband. Varje grupp består av fyra ord.",
    puzzle: {
      type: "connections",
      cooldownMs: 5 * 60 * 1000,
      mistakesBeforeCooldown: 3,
      groups: [
        {
          id: "band",
          title: "Band",
          words: ["PARKWAY DRIVE", "METALLICA", "GHOST", "JOURNEY"],
        },
        {
          id: "marstrand",
          title: "Marstrand",
          words: ["FERRY", "FORTRESS", "CHURCH", "SEA"],
        },
        {
          id: "brollopsresan",
          title: "Bröllopsresan",
          words: ["GOLF", "WHISKY", "HARRY POTTER", "HIGHLANDS"],
        },
        {
          id: "brollopsfesten",
          title: "Bröllopsfesten",
          words: ["TOAST", "CAKE", "DANCING", "SPEECHES"],
        },
      ],
    },
  },
  {
    id: "uppdrag-3",
    page: "uppdrag-3.html",
    title: "Namnen bakom mysteriet",
    unlockAt: null,
    hintUnlockAt: "2026-08-01T18:30:00",
    hintText: "Placeholder-ledtråd för uppdrag 3.",
    requires: "uppdrag-2",
    clue: "Avkoda ledtråden och skriv in namnet på personen vi söker.",
    puzzle: {
      type: "a1z26-person",
      encodedText: "2 18 21 4 5 14 19   13 15 18",
      decodedText: "BRUDENS MOR",
      acceptedAnswers: ["ELINA"],
      successTitle: "Rätt!",
      successText: "",
    },
  },
  {
    id: "uppdrag-4",
    page: "uppdrag-4.html",
    title: "Siffrorna mellan oss",
    unlockAt: null,
    hintUnlockAt: "2026-08-01T19:00:00",
    hintText: "Placeholder-ledtråd för uppdrag 4.",
    requires: "uppdrag-3",
    puzzle: {
      type: "sudoku",
      solution: "534678912672195348198342567859761423426853791713924856961537284287419635345286179",
      givens: [
        { cell: 0, value: "5", clue: "Antal spelare i ett lag i Pontus favoritspel League of Legends." },
        { cell: 1, value: "3", clue: "Entalssiffran i π." },
        { cell: 4, value: "7", clue: "Platshållare: byt till en ledtråd som ger siffran 7." },
        { cell: 9, value: "6", clue: "Förknippad med att skaffa barn." },
        { cell: 12, value: "1", clue: "Platshållare: byt till en ledtråd som ger siffran 1." },
        { cell: 13, value: "9", clue: "Platshållare: byt till en ledtråd som ger siffran 9." },
        { cell: 14, value: "5", clue: "Platshållare: byt till en ledtråd som ger siffran 5." },
        { cell: 19, value: "9", clue: "Platshållare: byt till en ledtråd som ger siffran 9." },
        { cell: 20, value: "8", clue: "Platshållare: byt till en ledtråd som ger siffran 8." },
        { cell: 25, value: "6", clue: "Platshållare: byt till en ledtråd som ger siffran 6." },
        { cell: 27, value: "8", clue: "Platshållare: byt till en ledtråd som ger siffran 8." },
        { cell: 31, value: "6", clue: "Platshållare: byt till en ledtråd som ger siffran 6." },
        { cell: 35, value: "3", clue: "Platshållare: byt till en ledtråd som ger siffran 3." },
        { cell: 36, value: "4", clue: "Platshållare: byt till en ledtråd som ger siffran 4." },
        { cell: 39, value: "8", clue: "Platshållare: byt till en ledtråd som ger siffran 8." },
        { cell: 41, value: "3", clue: "Platshållare: byt till en ledtråd som ger siffran 3." },
        { cell: 44, value: "1", clue: "Platshållare: byt till en ledtråd som ger siffran 1." },
        { cell: 45, value: "7", clue: "Platshållare: byt till en ledtråd som ger siffran 7." },
        { cell: 49, value: "2", clue: "Platshållare: byt till en ledtråd som ger siffran 2." },
        { cell: 53, value: "6", clue: "Platshållare: byt till en ledtråd som ger siffran 6." },
        { cell: 55, value: "6", clue: "Platshållare: byt till en ledtråd som ger siffran 6." },
        { cell: 60, value: "2", clue: "Platshållare: byt till en ledtråd som ger siffran 2." },
        { cell: 61, value: "8", clue: "Platshållare: byt till en ledtråd som ger siffran 8." },
        { cell: 66, value: "4", clue: "Platshållare: byt till en ledtråd som ger siffran 4." },
        { cell: 67, value: "1", clue: "Platshållare: byt till en ledtråd som ger siffran 1." },
        { cell: 68, value: "9", clue: "Platshållare: byt till en ledtråd som ger siffran 9." },
        { cell: 71, value: "5", clue: "Platshållare: byt till en ledtråd som ger siffran 5." },
        { cell: 76, value: "8", clue: "Platshållare: byt till en ledtråd som ger siffran 8." },
        { cell: 79, value: "7", clue: "Platshållare: byt till en ledtråd som ger siffran 7." },
        { cell: 80, value: "9", clue: "Platshållare: byt till en ledtråd som ger siffran 9." },
      ],
      clues: [],
    },
  },
  {
    id: "final",
    page: "final.html",
    title: "Final",
    unlockAt: null,
    requires: "uppdrag-4",
  },
];

const mysteryStorageKeys = {
  progress: "weddingMystery.progress",
  wordle: "weddingMystery.wordle.uppdrag-1",
  connections: "weddingMystery.connections.uppdrag-2",
  cipher: "weddingMystery.cipher.uppdrag-3",
  sudoku: "weddingMystery.sudoku.uppdrag-4",
};
