const mysteryHome = {
  countdownTarget: "2026-08-01T17:30:00",
};

const mysterySteps = [
  {
    id: "uppdrag-1",
    page: "uppdrag-1.html",
    title: "Ordlåset",
    unlockAt: null,
    hintUnlockAt: "2026-08-01T17:30:00",
    hintText: "Brudens smeknamn",
    requires: null,
    clue: "Lös det fem bokstäver långa ordet för att komma vidare.",
    answer: "SARRI",
    puzzle: {
      type: "wordle",
      answer: "SARRI",
      maxAttempts: null,
      visibleRows: 6,
    },
  },
  {
    id: "uppdrag-2",
    page: "uppdrag-2.html",
    title: "Trådarna mellan oss",
    unlockAt: null,
    hintUnlockAt: "2026-08-01T18:00:00",
    hintText: "Kategorier",
    requires: "uppdrag-1",
    clue: "Hitta fyra dolda samband. Varje grupp består av fyra ord.",
    puzzle: {
      type: "connections",
      cooldownMs: 5 * 60 * 1000,
      mistakesBeforeCooldown: 3,
      groups: [
        {
          id: "band",
          title: "Band",
          words: ["PARKWAY DRIVE", "METALLICA", "GHOST", "JOURNEY"],
        },
        {
          id: "marstrand",
          title: "Marstrand",
          words: ["FERRY", "FORTRESS", "CHURCH", "SEA"],
        },
        {
          id: "brollopsresan",
          title: "Bröllopsresan",
          words: ["GOLF", "WHISKY", "HARRY POTTER", "HIGHLANDS"],
        },
        {
          id: "brollopsfesten",
          title: "Bröllopsfesten",
          words: ["TOAST", "CAKE", "DANCING", "SPEECHES"],
        },
      ],
    },
  },
  {
    id: "uppdrag-3",
    page: "uppdrag-3.html",
    title: "Namnen bakom mysteriet",
    unlockAt: null,
    hintUnlockAt: "2026-08-01T18:30:00",
    hintText: "Alfabetet",
    requires: "uppdrag-2",
    clue: "Avkoda ledtråden och skriv in namnet på personen vi söker.",
    puzzle: {
      type: "a1z26-person",
      encodedText: "2 18 21 4 5 14 19   13 15 18",
      decodedText: "BRUDENS MOR",
      acceptedAnswers: ["ELINA"],
      successTitle: "Rätt!",
      successText: "",
    },
  },
  {
    id: "uppdrag-4",
    page: "uppdrag-4.html",
    title: "Siffrorna mellan oss",
    unlockAt: null,
    hintUnlockAt: "2026-08-01T19:00:00",
    hintText: "Visa startsiffrorna",
    requires: "uppdrag-3",
    puzzle: {
      type: "sudoku",
      solution: "534678912672195348198342567859761423426853791713924856961537284287419635345286179",
      givens: [
        { cell: 0, value: "5", clue: "Antal spelare i ett lag i Pontus favoritspel League of Legends." },
        { cell: 1, value: "3", clue: "Entalssiffran i π." },
        { cell: 4, value: "7", clue: "Yngsta årskursen Pontus undervisar." },
        { cell: 9, value: "6", clue: "Förknippad med att skaffa barn." },
        { cell: 12, value: "1", clue: "Antal syskon brudgummen har." },
        { cell: 13, value: "9", clue: "Antal månader en bebis bakas." },
        { cell: 14, value: "5", clue: "Antal kusiner brudgummen har." },
        { cell: 19, value: "9", clue: "Största entalssiffran." },
        { cell: 20, value: "8", clue: "Antal göteborgare som bor i Kanadas huvudstad." },
        { cell: 25, value: "6", clue: "(3 + 4 * 2) - 5." },
        { cell: 27, value: "8", clue: "En spindel har så här många ben." },
        { cell: 31, value: "6", clue: "Bäst i Yatzy." },
        { cell: 35, value: "3", clue: "Antal länder i Skandinavien." },
        { cell: 36, value: "4", clue: "Pater Noster + A (Fråga en bohuslänning)." },
        { cell: 39, value: "8", clue: "Antal planeter i solsystemet." },
        { cell: 41, value: "3", clue: "Ålderskillnaden på brudparet." },
        { cell: 44, value: "1", clue: "Lätt som en." },
        { cell: 45, value: "7", clue: "Antal sjösjuka sjömän som var ute på sjön." },
        { cell: 49, value: "2", clue: "Antal katter brudparet har." },
        { cell: 53, value: "6", clue: "Antal bokstäver i brudgummens namn." },
        { cell: 55, value: "6", clue: "Vi har lyssnat på prästen prata om Gud, men 3 st av denna siffra är förknippad med en arg grabb med hovar och treudd." },
        { cell: 60, value: "2", clue: "Antal lägenheter brudparet har bott i tillsammans." },
        { cell: 61, value: "8", clue: "Atomnummer för syre." },
        { cell: 66, value: "4", clue: "Hur länge har brudparet varit tillsammans? Avrunda till närmsta hela år." },
        { cell: 67, value: "1", clue: "Antal ringar Frodo och Sam skulle förstöra i Domedagsberget." },
        { cell: 68, value: "9", clue: "Antal liv Ace har." },
        { cell: 71, value: "5", clue: "Jackson _." },
        { cell: 76, value: "8", clue: "🐀 - R." },
        { cell: 79, value: "7", clue: "Antal Harry Potter-böcker i huvudserien." },
        { cell: 80, value: "9", clue: "3²." },
      ],
      clues: [],
    },
  },
  {
    id: "avslutning",
    page: "avslutning.html",
    title: "Det förseglade brevet",
    unlockAt: null,
    hintUnlockAt: null,
    hintText: "",
    requires: "uppdrag-4",
    ending: true,
  },
];

const mysteryStorageKeys = {
  progress: "weddingMystery.progress",
  wordle: "weddingMystery.wordle.uppdrag-1",
  connections: "weddingMystery.connections.uppdrag-2",
  cipher: "weddingMystery.cipher.uppdrag-3",
  sudoku: "weddingMystery.sudoku.uppdrag-4",
  ending: "weddingMystery.ending",
};
